### ISSUE TITLE
Deployment Error on VPS

### ISSUE THREAD

**Issue by Ekankth** [TeamKillerX/DarkWeb#8]
ubuntu@ip-172-31-8-138:~/DarkWeb$ python3 -m DarkWeb
Client1: Found.. Starting..
tgcalls v3.0.0.5 DEV, Copyright (C) 2020-2021 Il`ya (Marshal) <https://git
hub.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPL
v3)
LOG: Mendirikan Bot token Booting..
Successfully Imported .bot.bot �🛠️
Successfully Imported .bot.inline �🛠️
Successfully Imported .bot.start �🛠️
Successfully Imported .randydev.administrator �🛠️
Successfully Imported .randydev.adminlist �🛠️
Successfully Imported .randydev.afk �🛠️
Successfully Imported .randydev.asupan �🛠️
Successfully Imported .randydev.broadcast �🛠️
Successfully Imported .randydev.carbon �🛠️
Successfully Imported .randydev.chatbot �🛠️
Successfully Imported .randydev.dev �🛠️
[WARNING] - DarkWeb.database.SQL - DB_URI is not configured. Features depe
nding on the database might have issues.
[INFO] - DarkWeb.database.SQL - 'NoneType' object has no attribute '_insta
ntiate_plugins'
[WARNING] - DarkWeb - Unable to run GBan and GMute command, no SQL connect
ion found
Traceback (most recent call last):
  File "/home/ubuntu/DarkWeb/DarkWeb/database/SQL/gban_sql.py", line 2, in
 <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unloc
ked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_rem
oved
  File "/home/ubuntu/DarkWeb/DarkWeb/modules/randydev/globals.py", line 35
, in <module>
    globals_init()
  File "/home/ubuntu/DarkWeb/DarkWeb/modules/randydev/globals.py", line 32
, in globals_init
    raise e
  File "/home/ubuntu/DarkWeb/DarkWeb/modules/randydev/globals.py", line 26
, in globals_init
    sql = import_module("DarkWeb.database.SQL.gban_sql")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_mo
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unloc
ked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_rem
oved
  File "/home/ubuntu/DarkWeb/DarkWeb/database/SQL/gban_sql.py", line 4, in
 <module>
    raise AttributeError
AttributeError
ubuntu@ip-172-31-8-138:~/DarkWeb

**Comment by Ekankth** [comment]
ISSUE RESOLVED

**Comment by Ekankth** [comment]
Closed
